name: CI/CD for React with DynamoDB

on:
  push:
    branches:
      - main

jobs:
  # Build Job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Dependencies
        run: |
          cd data
          npm install

      - name: Build Project
        run: |
          cd data
          npm run build

      - name: Upload Artifact for Deployment
        uses: actions/upload-artifact@v3
        with:
          name: production-file
          path: ./data/build

  # Deploy Job
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: production-file
          path: ./data/build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.KEY }} 
          publish_dir: ./data/build

  # DynamoDB Update Job
  update-dynamodb:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update DynamoDB Table
        run: |
          aws dynamodb put-item \
            --table-name YourTableName \
            --item '{"id": {"S": "1"}, "name": {"S": "John Doe"}, "status": {"S": "Updated by CI/CD"}}'
